from pathlib import Path

PLAYER = Path('lib/screens/player_screen.dart')
LIVE = Path('lib/widgets/live_video_view.dart')
NATIVE = Path('lib/widgets/native_live_player_view.dart')

player = PLAYER.read_text()
live = LIVE.read_text()


def replace_once(text: str, old: str, new: str, label: str) -> str:
    if old not in text:
        if new in text:
            return text
        raise SystemExit(f'{label} marker not found')
    return text.replace(old, new, 1)


# ---------------------------------------------------------------------------
# Dart bridge: a Flutter PlatformView backed by Android Media3 PlayerView.
# The Android side is generated by the V3 workflow after `flutter create`.
# ---------------------------------------------------------------------------
NATIVE.write_text(r'''import 'dart:async';

import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

class NativeLivePlayerController {
  NativeLivePlayerController(int viewId)
      : _channel = MethodChannel('tvfull/media3_live_$viewId') {
    _channel.setMethodCallHandler(_handleNativeCall);
  }

  final MethodChannel _channel;
  final StreamController<Map<String, dynamic>> _events =
      StreamController<Map<String, dynamic>>.broadcast();
  bool _disposed = false;

  Stream<Map<String, dynamic>> get events => _events.stream;

  Future<dynamic> _handleNativeCall(MethodCall call) async {
    if (_disposed || call.method != 'event') return null;
    final raw = call.arguments;
    if (raw is Map) {
      _events.add(
        raw.map((key, value) => MapEntry(key.toString(), value)),
      );
    }
    return null;
  }

  Future<void> open({
    required String url,
    required Map<String, String> headers,
  }) async {
    await _channel.invokeMethod<void>('open', <String, dynamic>{
      'url': url,
      'headers': headers,
    });
  }

  Future<void> playPause() => _channel.invokeMethod<void>('playPause');

  Future<void> setVolume(double value) => _channel.invokeMethod<void>(
        'setVolume',
        <String, dynamic>{'value': value.clamp(0, 100).toDouble()},
      );

  Future<void> setResizeMode(int mode) => _channel.invokeMethod<void>(
        'setResizeMode',
        <String, dynamic>{'mode': mode},
      );

  Future<void> stop() => _channel.invokeMethod<void>('stop');

  Future<void> disposeController() async {
    if (_disposed) return;
    _disposed = true;
    _channel.setMethodCallHandler(null);
    await _events.close();
  }
}

class NativeLivePlayerSurface extends StatefulWidget {
  const NativeLivePlayerSurface({
    super.key,
    required this.onCreated,
  });

  final ValueChanged<NativeLivePlayerController> onCreated;

  @override
  State<NativeLivePlayerSurface> createState() =>
      _NativeLivePlayerSurfaceState();
}

class _NativeLivePlayerSurfaceState extends State<NativeLivePlayerSurface> {
  NativeLivePlayerController? _controller;

  @override
  void dispose() {
    final controller = _controller;
    if (controller != null) {
      unawaited(controller.disposeController());
    }
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return AndroidView(
      viewType: 'tvfull/media3_live_surface',
      onPlatformViewCreated: (viewId) {
        final controller = NativeLivePlayerController(viewId);
        _controller = controller;
        widget.onCreated(controller);
      },
    );
  }
}
''')

# ---------------------------------------------------------------------------
# LiveVideoView: preserve the existing TV FULL controls/UI, but allow LIVE to
# place a native SurfaceView underneath them. VOD continues to use media_kit.
# ---------------------------------------------------------------------------
live = replace_once(
    live,
    "  final bool isLiveContent;\n\n  final String title;\n",
    """  final bool isLiveContent;\n\n  // V3: sólo LIVE puede usar una superficie Media3 nativa. Películas/series\n  // siguen usando media_kit sin cambios.\n  final Widget? nativeLiveSurface;\n  final bool nativeLivePlaying;\n  final bool nativeLiveBuffering;\n  final double nativeLiveVolume;\n  final VoidCallback? onNativeLivePlayPause;\n  final ValueChanged<double>? onNativeLiveVolume;\n  final ValueChanged<int>? onNativeLiveFit;\n\n  final String title;\n""",
    'live native fields',
)

live = replace_once(
    live,
    "    required this.isLiveContent,\n    required this.title,\n",
    """    required this.isLiveContent,\n    this.nativeLiveSurface,\n    this.nativeLivePlaying = false,\n    this.nativeLiveBuffering = true,\n    this.nativeLiveVolume = 100,\n    this.onNativeLivePlayPause,\n    this.onNativeLiveVolume,\n    this.onNativeLiveFit,\n    required this.title,\n""",
    'live constructor native args',
)

live = replace_once(
    live,
    "  int _fitIndex = 0;\n\n  @override\n  void initState() {\n",
    """  int _fitIndex = 0;\n\n  bool get _usesNativeLive =>\n      widget.isLiveContent && widget.nativeLiveSurface != null;\n\n  @override\n  void initState() {\n""",
    'native live getter',
)

initial_state_old = """    _position = widget.player.state.position;\n    _duration = widget.player.state.duration;\n    _playing = widget.player.state.playing;\n    _buffering = widget.player.state.buffering;\n    _volume = widget.player.state.volume;\n    _audioTracks = widget.player.state.tracks.audio;\n    _subtitleTracks = widget.player.state.tracks.subtitle;\n    _selectedAudioTrack = widget.player.state.track.audio;\n    _selectedSubtitleTrack = widget.player.state.track.subtitle;\n"""
initial_state_new = """    if (_usesNativeLive) {\n      _playing = widget.nativeLivePlaying;\n      _buffering = widget.nativeLiveBuffering;\n      _volume = widget.nativeLiveVolume;\n      _hasStarted = _playing || !_buffering;\n    } else {\n      _position = widget.player.state.position;\n      _duration = widget.player.state.duration;\n      _playing = widget.player.state.playing;\n      _buffering = widget.player.state.buffering;\n      _volume = widget.player.state.volume;\n      _audioTracks = widget.player.state.tracks.audio;\n      _subtitleTracks = widget.player.state.tracks.subtitle;\n      _selectedAudioTrack = widget.player.state.track.audio;\n      _selectedSubtitleTrack = widget.player.state.track.subtitle;\n    }\n"""
live = replace_once(live, initial_state_old, initial_state_new, 'live initial state')

# Prevent idle media_kit state from overwriting Media3 state in LIVE mode.
live = live.replace(
    "if (!mounted) return;\n      final changed = value != _position;",
    "if (!mounted || _usesNativeLive) return;\n      final changed = value != _position;",
    1,
)
live = live.replace(
    "if (!mounted || value == _duration) return;",
    "if (!mounted || _usesNativeLive || value == _duration) return;",
    1,
)
# The next three listeners begin with the same mounted guard. Patch by anchors.
for anchor in [
    "_playingSub = widget.player.stream.playing.listen((value) {",
    "_bufferingSub = widget.player.stream.buffering.listen((value) {",
    "_volumeSub = widget.player.stream.volume.listen((value) {",
]:
    start = live.find(anchor)
    if start == -1:
        raise SystemExit(f'{anchor} not found')
    guard = live.find("if (!mounted) return;", start)
    if guard == -1 or guard > start + 220:
        raise SystemExit(f'mounted guard not found after {anchor}')
    live = live[:guard] + "if (!mounted || _usesNativeLive) return;" + live[guard + len("if (!mounted) return;"):]

# VOD track listeners already return for live content, so they need no change.

# Keep the existing overlay state synchronized from the Media3 parent state.
did_update = r'''
  @override
  void didUpdateWidget(covariant LiveVideoView oldWidget) {
    super.didUpdateWidget(oldWidget);
    if (!_usesNativeLive) return;
    _playing = widget.nativeLivePlaying;
    _buffering = widget.nativeLiveBuffering;
    _volume = widget.nativeLiveVolume;
    if (_playing) {
      _hasStarted = true;
      _lastProgressAt = DateTime.now();
    }
  }

'''
live = replace_once(
    live,
    "  bool get _isActuallyLive {\n",
    did_update + "  bool get _isActuallyLive {\n",
    'didUpdateWidget insertion',
)
live = replace_once(
    live,
    """  bool get _isActuallyLive {\n    if (!_hasStarted || !_playing || _buffering) return false;\n    return DateTime.now().difference(_lastProgressAt) <\n        const Duration(milliseconds: 2500);\n  }\n""",
    """  bool get _isActuallyLive {\n    if (!_hasStarted || !_playing || _buffering) return false;\n    if (_usesNativeLive) return true;\n    return DateTime.now().difference(_lastProgressAt) <\n        const Duration(milliseconds: 2500);\n  }\n""",
    'native live status',
)

live = replace_once(
    live,
    "  void _toggleFit(VideoState videoState) {\n",
    "  void _toggleFit(VideoState? videoState) {\n",
    'nullable fit state',
)
live = replace_once(
    live,
    "    videoState.update(fit: _videoFit);\n",
    """    if (_usesNativeLive) {\n      widget.onNativeLiveFit?.call(_fitIndex);\n    } else {\n      videoState?.update(fit: _videoFit);\n    }\n""",
    'native fit callback',
)
live = replace_once(
    live,
    "  Future<void> _handleBack(VideoState videoState) async {\n",
    "  Future<void> _handleBack(VideoState? videoState) async {\n",
    'nullable back state',
)
live = live.replace(
    "    if (videoState.isFullscreen()) {\n      await videoState.exitFullscreen();",
    "    if (videoState != null && videoState.isFullscreen()) {\n      await videoState.exitFullscreen();",
    1,
)
live = replace_once(
    live,
    "  Future<void> _handleChannelList(VideoState videoState) async {\n",
    "  Future<void> _handleChannelList(VideoState? videoState) async {\n",
    'nullable channel-list state',
)
live = live.replace(
    "    if (videoState.isFullscreen()) {\n      await videoState.exitFullscreen();",
    "    if (videoState != null && videoState.isFullscreen()) {\n      await videoState.exitFullscreen();",
    1,
)

live = replace_once(
    live,
    """  void _togglePlayPause() {\n    _showOverlay();\n    unawaited(widget.player.playOrPause());\n  }\n""",
    """  void _togglePlayPause() {\n    _showOverlay();\n    if (_usesNativeLive) {\n      widget.onNativeLivePlayPause?.call();\n      return;\n    }\n    unawaited(widget.player.playOrPause());\n  }\n""",
    'native play pause',
)
live = replace_once(
    live,
    """  void _setVolume(double value) {\n    _showOverlay();\n    setState(() => _volume = value);\n    unawaited(widget.player.setVolume(value));\n  }\n""",
    """  void _setVolume(double value) {\n    _showOverlay();\n    setState(() => _volume = value);\n    if (_usesNativeLive) {\n      widget.onNativeLiveVolume?.call(value);\n      return;\n    }\n    unawaited(widget.player.setVolume(value));\n  }\n""",
    'native volume',
)

# Replace the V2 Video(Texture) build with SurfaceView + the exact same Flutter
# overlay controls for LIVE. VOD remains the original media_kit Video widget.
build_start = live.find("  @override\n  Widget build(BuildContext context) {", live.find("KeyEventResult _handleTvRemoteKey"))
build_end = live.find("\n  Widget _buildControls(VideoState videoState)", build_start)
if build_start == -1 or build_end == -1:
    raise SystemExit('V2 LiveVideoView build block not found')
new_build = r'''  @override
  Widget build(BuildContext context) {
    final videoContent = _usesNativeLive
        ? Stack(
            fit: StackFit.expand,
            children: [
              widget.nativeLiveSurface!,
              _buildControls(null),
            ],
          )
        : Video(
            controller: widget.controller,
            fit: _videoFit,
            controls: (videoState) => _buildControls(videoState),
          );

    return FocusTraversalGroup(
      policy: ReadingOrderTraversalPolicy(),
      child: Focus(
        focusNode: _remoteFocusNode,
        autofocus: true,
        onKeyEvent: _handleTvRemoteKey,
        child: MouseRegion(
          onHover: (_) => _showOverlay(),
          child: Listener(
            behavior: HitTestBehavior.translucent,
            onPointerDown: (_) => _showOverlay(),
            child: videoContent,
          ),
        ),
      ),
    );
  }
'''
live = live[:build_start] + new_build + live[build_end:]

live = replace_once(
    live,
    "  Widget _buildControls(VideoState videoState) {\n",
    "  Widget _buildControls(VideoState? videoState) {\n",
    'nullable controls state',
)
live = replace_once(
    live,
    "  Widget _buildTopBar(VideoState videoState) {\n",
    "  Widget _buildTopBar(VideoState? videoState) {\n",
    'nullable topbar state',
)
live = replace_once(
    live,
    "  Widget _buildBottomArea(VideoState videoState) {\n",
    "  Widget _buildBottomArea(VideoState? videoState) {\n",
    'nullable bottom state',
)
live = replace_once(
    live,
    "  Widget _buildControlRow(VideoState videoState, bool compact) {\n",
    "  Widget _buildControlRow(VideoState? videoState, bool compact) {\n",
    'nullable control row state',
)

fullscreen_old = """        const SizedBox(width: 10),\n        _iconPill(\n          icon: videoState.isFullscreen()\n              ? Icons.fullscreen_exit_rounded\n              : Icons.fullscreen_rounded,\n          tooltip: videoState.isFullscreen()\n              ? 'Salir de pantalla completa'\n              : 'Pantalla completa',\n          onTap: () {\n            _showOverlay();\n            unawaited(videoState.toggleFullscreen());\n          },\n        ),\n"""
fullscreen_new = """        if (videoState != null) ...[\n          const SizedBox(width: 10),\n          _iconPill(\n            icon: videoState.isFullscreen()\n                ? Icons.fullscreen_exit_rounded\n                : Icons.fullscreen_rounded,\n            tooltip: videoState.isFullscreen()\n                ? 'Salir de pantalla completa'\n                : 'Pantalla completa',\n            onTap: () {\n              _showOverlay();\n              unawaited(videoState.toggleFullscreen());\n            },\n          ),\n        ],\n"""
live = replace_once(live, fullscreen_old, fullscreen_new, 'native fullscreen control')

# ---------------------------------------------------------------------------
# PlayerScreen: route only LIVE through Media3. The existing media_kit Player,
# tuning, tracks, VOD controls and compatibility code remain intact for VOD.
# ---------------------------------------------------------------------------
if "../widgets/native_live_player_view.dart" not in player:
    player = player.replace(
        "import '../widgets/live_video_view.dart';",
        "import '../widgets/live_video_view.dart';\nimport '../widgets/native_live_player_view.dart';",
        1,
    )

player = replace_once(
    player,
    "  StreamSubscription? _logSub;\n\n  int get _maxAutoRetries",
    """  StreamSubscription? _logSub;\n  StreamSubscription<Map<String, dynamic>>? _nativeLiveEventsSub;\n  NativeLivePlayerController? _nativeLiveController;\n  Timer? _nativeLiveReconnectTimer;\n  double _nativeLiveVolume = 100;\n\n  bool get _useMedia3Live => widget.isLiveContent;\n\n  int get _maxAutoRetries""",
    'player native fields',
)

# In LIVE V3, do not run the media_kit watchdog or start libmpv. Playback begins
# when AndroidView reports its native SurfaceView ready.
player = replace_once(
    player,
    """    _watchdogTimer = Timer.periodic(_watchdogInterval, (_) => _checkStall());\n\n    unawaited(_initializeAndPlay());\n""",
    """    if (!_useMedia3Live) {\n      _watchdogTimer = Timer.periodic(_watchdogInterval, (_) => _checkStall());\n      unawaited(_initializeAndPlay());\n    }\n""",
    'disable mpv live startup',
)

native_methods = r'''
  void _onNativeLiveViewCreated(NativeLivePlayerController controller) {
    if (!mounted || !_useMedia3Live) return;
    _nativeLiveEventsSub?.cancel();
    _nativeLiveController = controller;
    _nativeLiveEventsSub = controller.events.listen(_handleNativeLiveEvent);
    unawaited(_playCurrent());
  }

  void _handleNativeLiveEvent(Map<String, dynamic> event) {
    if (!mounted || !_useMedia3Live) return;
    final type = event['type']?.toString() ?? '';
    final eventSession = event['session'];
    if (eventSession is int && eventSession != _sessionId) return;

    switch (type) {
      case 'buffering':
        setState(() {
          _isBuffering = true;
          _engineDiagnostic = 'Media3 · recibiendo buffer';
        });
        return;
      case 'ready':
        setState(() {
          _isBuffering = false;
          _reconnecting = false;
        });
        return;
      case 'isPlaying':
        final value = event['value'] == true;
        setState(() {
          _isPlaying = value;
          if (value) _isBuffering = false;
        });
        return;
      case 'firstFrame':
        _confirmMedia3LiveStarted();
        return;
      case 'videoSize':
        final width = event['width'];
        final height = event['height'];
        final fps = event['fps'];
        setState(() {
          if (width is int && width > 0) _videoWidth = width;
          if (height is int && height > 0) _videoHeight = height;
          if (fps is num && fps > 0) _videoFps = fps.toDouble();
        });
        return;
      case 'surface':
        final value = event['value']?.toString() ?? 'desconocida';
        setState(() {
          _engineDiagnostic = 'Media3 + $value · render nativo Android TV';
        });
        return;
      case 'ended':
        _scheduleMedia3LiveReconnect('Media3 recibió fin de señal');
        return;
      case 'error':
        final message = event['message']?.toString() ?? 'Error Media3';
        _handleMedia3LiveFailure(message);
        return;
    }
  }

  void _confirmMedia3LiveStarted() {
    if (!mounted || !_useMedia3Live) return;
    _connectTimeoutTimer?.cancel();
    _nativeLiveReconnectTimer?.cancel();
    _hasEverPlayed = true;
    _isPlaying = true;
    _isBuffering = false;
    _reconnecting = false;
    _retryCount = 0;
    _lastProgressAt = DateTime.now();

    int? elapsed;
    if (_startupStopwatch?.isRunning ?? false) {
      _startupStopwatch!.stop();
      elapsed = _startupStopwatch!.elapsedMilliseconds;
    }
    int? zapElapsed;
    if ((_zapStopwatch?.isRunning ?? false) && _zapSession == _sessionId) {
      _zapStopwatch!.stop();
      zapElapsed = _zapStopwatch!.elapsedMilliseconds;
      _zapSession = null;
    }

    final url = _startupUrl;
    setState(() {
      if (elapsed != null) _lastStartupMs = elapsed;
      if (zapElapsed != null) _lastZapMs = zapElapsed;
      _engineDiagnostic = 'Media3 + SurfaceView · primer frame confirmado';
    });
    if (url != null && elapsed != null) {
      unawaited(_metrics.recordStartup(url, elapsed));
      if (zapElapsed != null) unawaited(_metrics.recordZap(url, zapElapsed));
    }
  }

  Future<void> _playCurrentMedia3({
    bool isRetry = false,
    bool isZap = false,
  }) async {
    final controller = _nativeLiveController;
    if (controller == null || !mounted) return;

    final session = ++_sessionId;
    _connectTimeoutTimer?.cancel();
    _retryTimer?.cancel();
    _nativeLiveReconnectTimer?.cancel();
    _errorTitle = null;
    _errorMessage = null;
    _opening = true;
    _hasEverPlayed = false;
    _isPlaying = false;
    _isBuffering = true;
    _reconnecting = isRetry;
    _lastProgressAt = DateTime.now();
    _startupStopwatch = Stopwatch()..start();
    _startupSession = session;

    if (isZap) {
      _zapStopwatch = Stopwatch()..start();
      _zapSession = session;
    } else if (isRetry && (_zapStopwatch?.isRunning ?? false)) {
      _zapSession = session;
    }

    final channel = widget.playlist[_currentIndex];
    _startupUrl = channel.url;
    final headers = channel.resolvedHttpHeaders(_defaultUserAgent);

    if (mounted) {
      setState(() {
        _engineDiagnostic = 'Media3 + SurfaceView · abriendo señal';
      });
    }

    try {
      await controller.open(url: channel.url, headers: headers);
      if (!mounted || session != _sessionId) return;
      _opening = false;
      final timeoutSeconds = widget.settings.connectTimeoutSeconds.clamp(6, 15);
      _connectTimeoutTimer = Timer(Duration(seconds: timeoutSeconds), () {
        if (!mounted || session != _sessionId || _hasEverPlayed) return;
        _handleMedia3LiveFailure('El canal no entregó el primer frame');
      });
    } catch (error) {
      if (!mounted || session != _sessionId) return;
      _opening = false;
      _handleMedia3LiveFailure('No se pudo abrir con Media3: $error');
    }
  }

  void _handleMedia3LiveFailure(String message) {
    if (!mounted || !_useMedia3Live) return;
    _connectTimeoutTimer?.cancel();
    final hadPlayback = _hasEverPlayed;
    final session = _sessionId;
    final maxRetries = widget.settings.maxRetries.clamp(1, 3);

    if (_retryCount < maxRetries) {
      final delayMs = hadPlayback ? 250 : 500 * (1 << _retryCount);
      _retryCount++;
      setState(() {
        _isBuffering = true;
        _reconnecting = true;
        _engineDiagnostic = '$message · reintento Media3 $_retryCount/$maxRetries';
      });
      _nativeLiveReconnectTimer?.cancel();
      _nativeLiveReconnectTimer = Timer(Duration(milliseconds: delayMs), () {
        if (!mounted || session != _sessionId) return;
        unawaited(_playCurrentMedia3(isRetry: true));
      });
      return;
    }

    _startupStopwatch?.stop();
    _zapStopwatch?.stop();
    _zapSession = null;
    setState(() {
      _isBuffering = false;
      _isPlaying = false;
      _reconnecting = false;
      _errorMessage = 'Este canal no responde con el reproductor Media3.\nProbá nuevamente o elegí otro canal.';
      _engineDiagnostic = message;
    });
  }

  void _scheduleMedia3LiveReconnect(String reason) {
    if (!mounted || !_useMedia3Live) return;
    _handleMedia3LiveFailure(reason);
  }

  void _toggleMedia3LivePlayPause() {
    final controller = _nativeLiveController;
    if (controller != null) unawaited(controller.playPause());
  }

  void _setMedia3LiveVolume(double value) {
    _nativeLiveVolume = value.clamp(0, 100).toDouble();
    final controller = _nativeLiveController;
    if (controller != null) unawaited(controller.setVolume(_nativeLiveVolume));
  }

  void _setMedia3LiveFit(int mode) {
    final controller = _nativeLiveController;
    if (controller != null) unawaited(controller.setResizeMode(mode));
  }

'''
player = replace_once(
    player,
    "  void _tryConfirmPlaybackFromDecodedOutput() {\n",
    native_methods + "  void _tryConfirmPlaybackFromDecodedOutput() {\n",
    'native media3 methods insertion',
)

# Route live opens/zaps/retries to Media3 before touching any mpv options.
play_signature = """  Future<void> _playCurrent({\n    bool isRetry = false,\n    bool forceNormalProbe = false,\n    bool skipStop = false,\n    bool isZap = false,\n    Duration? resumePosition,\n  }) async {\n"""
play_signature_v3 = play_signature + """    if (_useMedia3Live) {\n      await _playCurrentMedia3(isRetry: isRetry, isZap: isZap);\n      return;\n    }\n\n"""
player = replace_once(player, play_signature, play_signature_v3, 'media3 live route')

# Native live metrics are already supplied by Media3 events; don't query idle mpv.
player = player.replace(
    """  Future<void> _refreshContainerFormat() async {\n    if (_runtimeFormatLoaded ||\n""",
    """  Future<void> _refreshContainerFormat() async {\n    if (_useMedia3Live) return;\n    if (_runtimeFormatLoaded ||\n""",
    1,
)
player = player.replace(
    """  Future<void> _refreshRuntimeStats() async {\n    if (_runtimeStatsBusy ||\n""",
    """  Future<void> _refreshRuntimeStats() async {\n    if (_useMedia3Live) return;\n    if (_runtimeStatsBusy ||\n""",
    1,
)

# Dispose the native event bridge but leave the PlatformView to release ExoPlayer
# from its own Android lifecycle callback.
player = replace_once(
    player,
    "    _logSub?.cancel();\n    unawaited(_player.dispose());\n",
    """    _logSub?.cancel();\n    _nativeLiveReconnectTimer?.cancel();\n    _nativeLiveEventsSub?.cancel();\n    final nativeController = _nativeLiveController;\n    if (nativeController != null) unawaited(nativeController.stop());\n    unawaited(_player.dispose());\n""",
    'native dispose',
)

# Preserve the exact TV FULL overlay. Only swap the video surface and live control
# callbacks; VOD key/path stays unchanged.
player = replace_once(
    player,
    """            child: LiveVideoView(\n              key: ValueKey(channel.uniqueKey),\n              player: _player,\n""",
    """            child: LiveVideoView(\n              key: widget.isLiveContent\n                  ? const ValueKey('tv-full-media3-live-view')\n                  : ValueKey(channel.uniqueKey),\n              player: _player,\n""",
    'stable native live key',
)
player = replace_once(
    player,
    """              isLiveContent: widget.isLiveContent,\n              title: channel.name,\n""",
    """              isLiveContent: widget.isLiveContent,\n              nativeLiveSurface: widget.isLiveContent\n                  ? NativeLivePlayerSurface(\n                      key: const ValueKey('tv-full-media3-surface'),\n                      onCreated: _onNativeLiveViewCreated,\n                    )\n                  : null,\n              nativeLivePlaying: _isPlaying,\n              nativeLiveBuffering: _isBuffering,\n              nativeLiveVolume: _nativeLiveVolume,\n              onNativeLivePlayPause:\n                  widget.isLiveContent ? _toggleMedia3LivePlayPause : null,\n              onNativeLiveVolume:\n                  widget.isLiveContent ? _setMedia3LiveVolume : null,\n              onNativeLiveFit:\n                  widget.isLiveContent ? _setMedia3LiveFit : null,\n              title: channel.name,\n""",
    'native live surface args',
)

PLAYER.write_text(player)
LIVE.write_text(live)
print('Android TV V3 Media3 + SurfaceView LIVE patch applied; VOD remains media_kit')
