name: iptv_player
description: TV FULL PRO para Android TV, rápido, liviano y orientado a control remoto.
publish_to: 'none'
version: 1.2.6+18

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  media_kit: ^1.2.6
  media_kit_video: ^2.0.1
  media_kit_libs_video: ^1.0.7
  provider: ^6.1.2
  http: ^1.2.2
  shared_preferences: ^2.3.2
  sqflite: ^2.4.2
  crypto: ^3.0.6
  path_provider: ^2.1.4
  url_launcher: ^6.3.2
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

# TV FULL PRO 1.2.6+18 remote-focus-scroll-update-fixes marker.
