from pathlib import Path

# --- Rendimiento UI ---
path = Path('lib/screens/playback_settings_screen.dart')
text = path.read_text()

old = """      _draft = switch (profile) {\n        BufferProfile.auto => PlaybackSettings.auto,\n        BufferProfile.ultraFast => PlaybackSettings.ultraFast,\n        BufferProfile.balanced => PlaybackSettings.balanced,\n        BufferProfile.stable => PlaybackSettings.stable,\n        BufferProfile.custom => _draft.copyWith(profile: BufferProfile.custom),\n      };\n"""
new = """      _draft = switch (profile) {\n        BufferProfile.auto => PlaybackSettings.auto,\n        BufferProfile.ultraFast => PlaybackSettings.ultraFast,\n        BufferProfile.balanced => PlaybackSettings.balanced,\n        BufferProfile.stable => PlaybackSettings.stable,\n        BufferProfile.slowConnection => PlaybackSettings.slowConnection,\n        BufferProfile.custom => _draft.copyWith(profile: BufferProfile.custom),\n      };\n"""
if old not in text:
    raise SystemExit('settings preset switch not found')
text = text.replace(old, new, 1)

old = """              Text(\n                _speedGuidance(result.downloadMbps),\n                style: const TextStyle(fontWeight: FontWeight.w600),\n              ),\n"""
new = """              Text(\n                _speedGuidance(result.downloadMbps),\n                style: const TextStyle(fontWeight: FontWeight.w600),\n              ),\n              if (result.downloadMbps < 15) ...[\n                const SizedBox(height: 14),\n                Container(\n                  padding: const EdgeInsets.all(14),\n                  decoration: BoxDecoration(\n                    color: Theme.of(context)\n                        .colorScheme\n                        .primary\n                        .withValues(alpha: 0.10),\n                    borderRadius: BorderRadius.circular(14),\n                    border: Border.all(\n                      color: Theme.of(context)\n                          .colorScheme\n                          .primary\n                          .withValues(alpha: 0.30),\n                    ),\n                  ),\n                  child: Row(\n                    children: [\n                      const Icon(Icons.wifi_tethering_error_rounded),\n                      const SizedBox(width: 12),\n                      const Expanded(\n                        child: Text(\n                          'Para esta velocidad conviene probar Conexión lenta. TV FULL reservará más video por adelantado y será más paciente ante microcortes.',\n                          style: TextStyle(fontWeight: FontWeight.w600),\n                        ),\n                      ),\n                      const SizedBox(width: 12),\n                      FilledButton(\n                        onPressed: () =>\n                            _applyPreset(BufferProfile.slowConnection),\n                        child: const Text('Activar'),\n                      ),\n                    ],\n                  ),\n                ),\n              ],\n"""
if old not in text:
    raise SystemExit('speed guidance block not found')
text = text.replace(old, new, 1)

old = """              _ProfileChip(\n                label: 'Estable',\n                icon: Icons.shield_outlined,\n                selected: _draft.profile == BufferProfile.stable,\n                onTap: () => _applyPreset(BufferProfile.stable),\n              ),\n              _ProfileChip(\n                label: 'Personalizado',\n"""
new = """              _ProfileChip(\n                label: 'Estable',\n                icon: Icons.shield_outlined,\n                selected: _draft.profile == BufferProfile.stable,\n                onTap: () => _applyPreset(BufferProfile.stable),\n              ),\n              _ProfileChip(\n                label: 'Conexión lenta',\n                icon: Icons.wifi_tethering_error_rounded,\n                selected: _draft.profile == BufferProfile.slowConnection,\n                onTap: () => _applyPreset(BufferProfile.slowConnection),\n              ),\n              _ProfileChip(\n                label: 'Personalizado',\n"""
if old not in text:
    raise SystemExit('profile chip insertion point not found')
text = text.replace(old, new, 1)

old = """          const SizedBox(height: 16),\n          _SliderTile(\n            title: 'Memoria de buffer',\n"""
new = """          if (_draft.profile == BufferProfile.slowConnection) ...[\n            const SizedBox(height: 16),\n            Card(\n              child: Padding(\n                padding: const EdgeInsets.all(16),\n                child: Column(\n                  crossAxisAlignment: CrossAxisAlignment.start,\n                  children: [\n                    const Row(\n                      children: [\n                        Icon(Icons.wifi_tethering_error_rounded),\n                        SizedBox(width: 8),\n                        Expanded(\n                          child: Text(\n                            'Modo conexión lenta',\n                            style: TextStyle(fontWeight: FontWeight.bold),\n                          ),\n                        ),\n                      ],\n                    ),\n                    const SizedBox(height: 8),\n                    const Text(\n                      'Prioriza continuidad sobre velocidad de arranque. En TV en vivo usa una reserva moderada para no alejarse demasiado del directo; en Películas y Series anticipa más datos. Durante la reproducción, TV FULL mantiene pausadas las descargas de portadas y logos.',\n                    ),\n                    const SizedBox(height: 8),\n                    const Text(\n                      'No reduce automáticamente la calidad y no puede compensar un stream cuyo bitrate sea permanentemente mayor que la velocidad disponible.',\n                      style: TextStyle(color: Colors.white60, fontSize: 12),\n                    ),\n                  ],\n                ),\n              ),\n            ),\n          ],\n          const SizedBox(height: 16),\n          _SliderTile(\n            title: 'Memoria de buffer',\n"""
if old not in text:
    raise SystemExit('slow connection info insertion point not found')
text = text.replace(old, new, 1)

old = """                'Ultra rápido prioriza el zapping. Estable usa más margen para redes irregulares. Automático aprende por servidor. Si movés cualquier control manual, el perfil cambia a Personalizado.',\n"""
new = """                'Ultra rápido prioriza el zapping. Estable usa más margen para redes irregulares. Conexión lenta aumenta la reserva y la tolerancia a microcortes. Automático aprende por servidor. Si movés cualquier control manual, el perfil cambia a Personalizado.',\n"""
if old not in text:
    raise SystemExit('profile help text not found')
text = text.replace(old, new, 1)
path.write_text(text)

# --- Player: tuning real y etiquetas ---
path = Path('lib/screens/player_screen.dart')
text = path.read_text()

old = """    final tunedSettings = tuning.settings;\n    final applyLiveStabilityFloor =\n        widget.isLiveContent && widget.settings.profile == BufferProfile.auto;\n    _effectiveSettings = applyLiveStabilityFloor\n        ? tunedSettings.copyWith(\n            bufferMb: tunedSettings.bufferMb < 16 ? 16 : tunedSettings.bufferMb,\n            readaheadSeconds: tunedSettings.readaheadSeconds < 2.5\n                ? 2.5\n                : tunedSettings.readaheadSeconds,\n            recoveryBufferSeconds: tunedSettings.recoveryBufferSeconds < 1.5\n                ? 1.5\n                : tunedSettings.recoveryBufferSeconds,\n            connectTimeoutSeconds: tunedSettings.connectTimeoutSeconds < 8\n                ? 8\n                : tunedSettings.connectTimeoutSeconds,\n            stallThresholdSeconds: tunedSettings.stallThresholdSeconds < 12\n                ? 12\n                : tunedSettings.stallThresholdSeconds,\n          )\n        : tunedSettings;\n    _tuningLabel = applyLiveStabilityFloor\n        ? '${tuning.label} · Live estable'\n        : tuning.label;\n"""
new = """    final tunedSettings = tuning.settings;\n    final slowConnection =\n        widget.settings.profile == BufferProfile.slowConnection;\n    final applyLiveStabilityFloor =\n        widget.isLiveContent && widget.settings.profile == BufferProfile.auto;\n\n    if (slowConnection) {\n      // Live necesita reserva, pero no queremos acumular un retraso enorme.\n      // VOD puede anticipar mucho más porque no existe borde en vivo.\n      _effectiveSettings = widget.isLiveContent\n          ? tunedSettings.copyWith(\n              bufferMb: 48,\n              readaheadSeconds: 6.0,\n              recoveryBufferSeconds: 4.0,\n              connectTimeoutSeconds: 15,\n              maxRetries: 5,\n              stallThresholdSeconds: 18,\n            )\n          : tunedSettings.copyWith(\n              bufferMb: 96,\n              readaheadSeconds: 12.0,\n              recoveryBufferSeconds: 5.0,\n              connectTimeoutSeconds: 15,\n              maxRetries: 5,\n              stallThresholdSeconds: 18,\n            );\n      _tuningLabel = widget.isLiveContent\n          ? 'Conexión lenta · Live protegido'\n          : 'Conexión lenta · VOD reforzado';\n    } else {\n      _effectiveSettings = applyLiveStabilityFloor\n          ? tunedSettings.copyWith(\n              bufferMb: tunedSettings.bufferMb < 16 ? 16 : tunedSettings.bufferMb,\n              readaheadSeconds: tunedSettings.readaheadSeconds < 2.5\n                  ? 2.5\n                  : tunedSettings.readaheadSeconds,\n              recoveryBufferSeconds: tunedSettings.recoveryBufferSeconds < 1.5\n                  ? 1.5\n                  : tunedSettings.recoveryBufferSeconds,\n              connectTimeoutSeconds: tunedSettings.connectTimeoutSeconds < 8\n                  ? 8\n                  : tunedSettings.connectTimeoutSeconds,\n              stallThresholdSeconds: tunedSettings.stallThresholdSeconds < 12\n                  ? 12\n                  : tunedSettings.stallThresholdSeconds,\n            )\n          : tunedSettings;\n      _tuningLabel = applyLiveStabilityFloor\n          ? '${tuning.label} · Live estable'\n          : tuning.label;\n    }\n"""
if old not in text:
    raise SystemExit('player tuning block not found')
text = text.replace(old, new, 1)

old = """    final liveGrace = widget.isLiveContent\n        ? Duration(\n            seconds: _stallThreshold.inSeconds < 30\n                ? 30\n                : _stallThreshold.inSeconds,\n          )\n        : _stallThreshold;\n    final bufferingGrace = widget.isLiveContent\n        ? Duration(\n            seconds: _stallThreshold.inSeconds + 20 < 45\n                ? 45\n                : _stallThreshold.inSeconds + 20,\n          )\n        : Duration(\n            seconds: _stallThreshold.inSeconds < 8\n                ? 12\n                : _stallThreshold.inSeconds + 4,\n          );\n"""
new = """    final slowConnection =\n        widget.settings.profile == BufferProfile.slowConnection;\n    final liveGrace = widget.isLiveContent\n        ? Duration(\n            seconds: slowConnection\n                ? 45\n                : (_stallThreshold.inSeconds < 30\n                    ? 30\n                    : _stallThreshold.inSeconds),\n          )\n        : Duration(\n            seconds: slowConnection\n                ? 30\n                : _stallThreshold.inSeconds,\n          );\n    final bufferingGrace = widget.isLiveContent\n        ? Duration(\n            seconds: slowConnection\n                ? 60\n                : (_stallThreshold.inSeconds + 20 < 45\n                    ? 45\n                    : _stallThreshold.inSeconds + 20),\n          )\n        : Duration(\n            seconds: slowConnection\n                ? 30\n                : (_stallThreshold.inSeconds < 8\n                    ? 12\n                    : _stallThreshold.inSeconds + 4),\n          );\n"""
if old not in text:
    raise SystemExit('watchdog grace block not found')
text = text.replace(old, new, 1)

old = """      BufferProfile.stable => 'Estable',\n      BufferProfile.custom => 'Personalizado',\n"""
new = """      BufferProfile.stable => 'Estable',\n      BufferProfile.slowConnection => 'Conexión lenta',\n      BufferProfile.custom => 'Personalizado',\n"""
if old not in text:
    raise SystemExit('player profile label switch not found')
text = text.replace(old, new, 1)

path.write_text(text)
