from pathlib import Path

path = Path('lib/services/xtream_series_service.dart')
text = path.read_text()

old = '''  final String extension;\n  final String? plot;\n  final String? duration;\n  final String? image;\n  final String? rating;\n\n  const XtreamSeriesEpisode({\n    required this.id,\n    required this.season,\n    required this.number,\n    required this.title,\n    required this.extension,\n    this.plot,\n    this.duration,\n    this.image,\n    this.rating,\n  });\n\n  Channel toChannel(XtreamConnectionResult connection, {String? group}) {\n    final prefix = connection.streamServer.pathSegments\n        .where((segment) => segment.trim().isNotEmpty)\n        .toList(growable: false);\n    final url = connection.streamServer\n        .replace(\n          pathSegments: [\n            ...prefix,\n            'series',\n            connection.username,\n            connection.password,\n            '$id.$extension',\n          ],\n          query: '',\n          fragment: '',\n        )\n        .toString();\n\n    return Channel(\n      name: title,\n      url: url,\n      logoUrl: image,\n      group: group,\n    );\n  }\n'''
new = '''  final String extension;\n  final String? directSource;\n  final String? plot;\n  final String? duration;\n  final String? image;\n  final String? rating;\n\n  const XtreamSeriesEpisode({\n    required this.id,\n    required this.season,\n    required this.number,\n    required this.title,\n    required this.extension,\n    this.directSource,\n    this.plot,\n    this.duration,\n    this.image,\n    this.rating,\n  });\n\n  Channel toChannel(XtreamConnectionResult connection, {String? group}) {\n    // Algunos paneles Xtream entregan una URL exacta por episodio. Si existe,\n    // es más fiable que reconstruir /series/... porque puede apuntar a otro\n    // host, CDN, puerto o contenedor.\n    final direct = _resolvedEpisodeDirectSource(\n      connection.streamServer,\n      directSource,\n    );\n\n    final prefix = connection.streamServer.pathSegments\n        .where((segment) => segment.trim().isNotEmpty)\n        .toList(growable: false);\n    final generated = connection.streamServer\n        .replace(\n          pathSegments: [\n            ...prefix,\n            'series',\n            connection.username,\n            connection.password,\n            '$id.$extension',\n          ],\n          query: '',\n          fragment: '',\n        )\n        .toString();\n\n    return Channel(\n      name: title,\n      url: direct ?? generated,\n      logoUrl: image,\n      group: group,\n    );\n  }\n\n  static String? _resolvedEpisodeDirectSource(Uri base, String? raw) {\n    final value = raw?.trim() ?? '';\n    if (value.isEmpty || value.toLowerCase() == 'null' || value == '0') {\n      return null;\n    }\n    final parsed = Uri.tryParse(value);\n    if (parsed != null &&\n        (parsed.scheme == 'http' || parsed.scheme == 'https') &&\n        parsed.host.isNotEmpty) {\n      return parsed.toString();\n    }\n    if (value.startsWith('/')) return base.resolve(value).toString();\n    return null;\n  }\n'''
if old not in text:
    raise SystemExit('episode class block not found')
text = text.replace(old, new, 1)

old = '''    final extension = _cleanExtension(item['container_extension']?.toString());\n\n    return XtreamSeriesEpisode(\n      id: id,\n      season: season <= 0 ? 1 : season,\n      number: number <= 0 ? 1 : number,\n      title: title,\n      extension: extension,\n      plot: _cleanText(info['plot']),\n'''
new = '''    final directSource = _firstText(\n      item,\n      const ['direct_source', 'directSource', 'stream_source'],\n    ) ?? _firstText(info, const ['direct_source', 'directSource', 'stream_source']);\n\n    // En clones/paneles Xtream la extensión puede vivir en el episodio o en\n    // info. También la inferimos de direct_source antes de usar un fallback.\n    final extension = _firstValidExtension([\n      item['container_extension'],\n      item['containerExtension'],\n      item['extension'],\n      info['container_extension'],\n      info['containerExtension'],\n      info['extension'],\n      _extensionFromUrl(directSource),\n    ]);\n\n    return XtreamSeriesEpisode(\n      id: id,\n      season: season <= 0 ? 1 : season,\n      number: number <= 0 ? 1 : number,\n      title: title,\n      extension: extension,\n      directSource: directSource,\n      plot: _cleanText(info['plot']),\n'''
if old not in text:
    raise SystemExit('episode parse block not found')
text = text.replace(old, new, 1)

old = '''  static String _cleanExtension(String? raw) {\n    final value = (raw ?? '').trim().toLowerCase().replaceFirst('.', '');\n    if (value.isEmpty || !RegExp(r'^[a-z0-9]{2,6}$').hasMatch(value)) {\n      return 'mp4';\n    }\n    return value;\n  }\n'''
new = '''  static String _firstValidExtension(Iterable<dynamic> candidates) {\n    for (final candidate in candidates) {\n      final value = candidate?.toString().trim().toLowerCase().replaceFirst('.', '') ?? '';\n      if (value.isNotEmpty && RegExp(r'^[a-z0-9]{2,6}$').hasMatch(value)) {\n        return value;\n      }\n    }\n    // mp4 sigue siendo el último fallback, pero ya no se usa si el panel\n    // declaró el contenedor en otro campo o dentro de direct_source.\n    return 'mp4';\n  }\n\n  static String? _extensionFromUrl(String? raw) {\n    final value = raw?.trim() ?? '';\n    if (value.isEmpty) return null;\n    final uri = Uri.tryParse(value);\n    final path = uri?.path ?? value;\n    final slash = path.lastIndexOf('/');\n    final file = slash >= 0 ? path.substring(slash + 1) : path;\n    final dot = file.lastIndexOf('.');\n    if (dot < 0 || dot == file.length - 1) return null;\n    return file.substring(dot + 1);\n  }\n'''
if old not in text:
    raise SystemExit('extension helper block not found')
text = text.replace(old, new, 1)

path.write_text(text)
